#!/usr/bin/env bash
# Fail when any commit reachable from REV credits someone other than the allowed
# identities, or carries a co-author, session-link or tool attribution line.
#
#   ALLOWED_EMAILS="you@users.noreply.github.com" bash scripts/check-commit-identity.sh [REV]
#
# Identity is checked by email, which is what GitHub uses to link a commit to an
# account. Merges made on GitHub's website are committed by GitHub itself, so that
# committer is accepted; their author must still be an allowed email.
set -euo pipefail
for dependency in git grep; do
  command -v "$dependency" >/dev/null 2>&1 || {
    echo "FAIL required command unavailable: $dependency" >&2
    exit 1
  }
done
rev=${1:-HEAD}
allowed=${ALLOWED_EMAILS:?set ALLOWED_EMAILS to the permitted author emails}
web_committer=noreply@github.com

is_allowed() { case " $allowed " in *" $1 "*) return 0 ;; esac; return 1; }

# Attribution lines, matched case-insensitively. Trailer-shaped credits always fail;
# a session trailer fails when its value is a link. "Generated with/by" fails only
# when it leads its line (an emoji or punctuation prefix is allowed) and names a link
# or a known AI tool, so prose such as "Generated by new-project.sh" still passes.
ai_tools='claude|codex|copilot|chatgpt|gpt|gemini|cursor|aider|devin'
attribution="^[[:space:]]*(co-authored-by|generated-by):"
attribution="$attribution|^[[:space:]]*[a-z0-9_-]+-session:[[:space:]]*<?https?://"
attribution="$attribution|^[^[:alnum:]]*generated (with|by)[[:space:]]+(\\[|<?https?://|($ai_tools)([^[:alnum:]]|\$))"

commits=$(git rev-list "$rev") || { echo "FAIL could not enumerate commits for $rev" >&2; exit 1; }
[ -n "$commits" ] || { echo "FAIL no commits found for $rev"; exit 1; }
checked=0
failures=0
while IFS= read -r sha; do
  checked=$((checked + 1))
  author_email=$(git log -1 --format=%ae "$sha")
  committer_email=$(git log -1 --format=%ce "$sha")
  label="${sha:0:7} $(git log -1 --format=%s "$sha")"
  if ! is_allowed "$author_email"; then
    echo "FAIL $label: author $(git log -1 --format='%an <%ae>' "$sha") is not allowed"
    failures=$((failures + 1))
  fi
  if ! is_allowed "$committer_email" && [ "$committer_email" != "$web_committer" ]; then
    echo "FAIL $label: committer $(git log -1 --format='%cn <%ce>' "$sha") is not allowed"
    failures=$((failures + 1))
  fi
  # Git Bash can classify emoji as alphanumeric in C.UTF-8. Match these ASCII
  # policy markers bytewise so Unicode prefixes cannot bypass attribution checks.
  message=$(git log -1 --format=%B "$sha") || {
    echo "FAIL could not read commit message for $sha" >&2; exit 1;
  }
  # Consume the whole message: grep -q can close early and make Git/printf fail
  # with SIGPIPE under pipefail, disguising a match as a failed condition.
  match_status=0
  printf '%s\n' "$message" | LC_ALL=C grep -iE "$attribution" >/dev/null || match_status=$?
  case "$match_status" in
    0)
      echo "FAIL $label: message contains a co-author or attribution line"
      failures=$((failures + 1)) ;;
    1) ;; # No matching attribution.
    *) echo "FAIL attribution matcher failed for $sha (exit $match_status)" >&2; exit 1 ;;
  esac
done <<< "$commits"

if [ "$checked" -eq 0 ]; then echo "FAIL no commits found for $rev"; exit 1; fi
if [ "$failures" -gt 0 ]; then echo "$failures problem(s) in $checked commit(s)"; exit 1; fi
echo "ok: $checked commit(s) credit only the allowed identity"
